// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAL.Entity
{
    public partial class uspGetProductListResult
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public int? BrandID { get; set; }
        public string Category { get; set; }
        public decimal Price { get; set; }
        public int? TotalCount { get; set; }
    }
}
